Hw02 express
TatyanaZaytseva/nodejs-homework-REST-API pull request #1
Opened 2023-01-03 11:45 UTC by TatyanaZaytseva

2023-01-03 12:17 UTC, KhYulian commented on app.js
> +  }
Модна скоротити запис скориставшись ||

2023-01-03 12:20 UTC, KhYulian commented on models/contacts.js
> +  await writeDB(db);
повертайте з цієї функції оновлений контакт

2023-01-03 12:21 UTC, KhYulian commented on controllers/contacts.controllers.js
> +  return res.status(200).json(updatedContact);
переускладнена логіка updateContact має повертати оновлений контак. Тоді не потрібно викликати getContqact

2023-01-03 12:21 UTC, KhYulian requested changes
Потрібне доопрацюювання

2023-01-03 12:22 UTC, KhYulian commented
Також подавайте роботу в ЛМС

2023-01-03 12:22 UTC, KhYulian commented
І відповідайте на коменти по мірі виправлення :)

2023-01-04 17:30 UTC, TatyanaZaytseva commented on app.js
> +  }
I can't imagine how to do it in this situation(((( Could you help me, please)))))

2023-01-04 17:30 UTC, TatyanaZaytseva commented on models/contacts.js
> +  await writeDB(db);
Done

2023-01-04 17:30 UTC, TatyanaZaytseva commented on controllers/contacts.controllers.js
> +  return res.status(200).json(updatedContact);
Yes, thank you. Already did it.

2023-01-04 17:32 UTC, KhYulian commented on app.js
> +  }
res.status(err.status || 500) - https://javascript.info/logical-operators

2023-01-04 17:35 UTC, KhYulian approved these changes
Good job ❤️

2023-01-04 17:36 UTC, KhYulian commented
You can fix this issue in the next homework - if (err.status) {
    return res.status(err.status).json({
      message: err.message,
    });
  }

2023-01-04 17:36 UTC, merged